port: "8081"

db:
  username: "postgres"
  host: "postgres_hezzl_api"  # Используется имя контейнера PostgreSQL
#  host: "localhost"
  port: "5432"
  dbname: "hezzl_api"
  sslmode: "disable"

clickhouse:
  username: "test"
  host: "clickhouse_hezzl_api"
#  host: "localhost"
  port: 9000
  dbname: "default"

redis:
  host: "redis_hezzl_api"
#  host: "localhost"
  port: 6379
  dbname: 0